<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
var carte;

	function initialiser() {
		var latlng = new google.maps.LatLng(43.1225865, 5.9348527);
		//objet contenant des propriétés avec des identificateurs prédéfinis dans Google Maps permettant
		//de définir des options d'affichage de notre carte
		var options = {
			center: latlng,
			zoom: 17,
			mapTypeId: google.maps.MapTypeId.ROADMAP
		};

		
		//constructeur de la carte qui prend en paramêtre le conteneur HTML
		//dans lequel la carte doit s'afficher et les options
		carte = new google.maps.Map(document.getElementById("carte"), options);

		<?php foreach ($this->pots as $pot):
		$potModel = new Application_Model_Pots();
		$greenpod = $potModel->getPotById($pot['pot_id']);

		?>
		var marqueur = new google.maps.Marker({
			position: new google.maps.LatLng(<?php echo $greenpod[0]['latitude']?>, <?php echo $greenpod[0]['longitude']?>),
			map: carte
		});

		<?php endforeach;?>

		$('.maposition').click(function()
				{
					if (navigator.geolocation)
					  navigator.geolocation.getCurrentPosition(successCallback, errorCallback);
					else
					  alert("Votre navigateur ne prend pas en compte la géolocalisation HTML5");
					   
					
					function successCallback(position){
						carte.setCenter(new google.maps.LatLng(position.coords.latitude, position.coords.longitude));
					};  
					 
					function errorCallback(error){
					  switch(error.code){
					    case error.PERMISSION_DENIED:
					      alert("L'utilisateur n'a pas autorisé l'accès à sa position");
					      break;      
					    case error.POSITION_UNAVAILABLE:
					      alert("L'emplacement de l'utilisateur n'a pas pu être déterminé");
					      break;
					    case error.TIMEOUT:
					      alert("Le service n'a pas répondu à temps");
					      break;
					    }
					};
				});
	}

	$(document).ready(function()
	{
		initialiser();

		if (navigator.geolocation)
			  navigator.geolocation.getCurrentPosition(successCallback, errorCallback);
			else
			  alert("Votre navigateur ne prend pas en compte la géolocalisation HTML5");

		function successCallback(position){
			carte.setCenter(new google.maps.LatLng(position.coords.latitude, position.coords.longitude));
		};  
		 
		function errorCallback(error){
		  switch(error.code){
		    case error.PERMISSION_DENIED:
		      alert("L'utilisateur n'a pas autorisé l'accès à sa position");
		      break;      
		    case error.POSITION_UNAVAILABLE:
		      alert("L'emplacement de l'utilisateur n'a pas pu être déterminé");
		      break;
		    case error.TIMEOUT:
		      alert("Le service n'a pas répondu à temps");
		      break;
		    }
		};   
		
	});
	
</script>



<div id="carte" style="width:100%; height:100%"></div>

<img class="maposition" src="<?php echo $this->baseUrl();?>/images/maposition.png" >

<script type="text/javascript">

	$('#interface').removeClass('interface');
	$('#interface').addClass('interface2');
	$('#imglogo').addClass('displayNone');
	$('.Vue').addClass('backgroundBleu');
	$('#textDescription').html('<h2>Carte</h2>');
	$('#texteDescription').html("<h1>Mon jardin dans ma rue</h1");
</script>