<div class="reseauSociau">
    <h2>Choisis ton réseau<br>préféré pour le dire</h2>
    <div>
        <a target="_blank" title="Twitter" href="https://twitter.com/share?url=http://www.teddypintat.fr/greenCityzen/auth/album/greenpodid/<?php echo $this->greenId;?>&text=&via=GreenCityZen" rel="nofollow" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=400,width=700');return false;"><img src="<?php echo $this->baseUrl();?>/images/twitter_2.png" alt="bouton partage twitter" width="50" height="50"/></a>

        <a target="_blank" title="Facebook" href="https://www.facebook.com/sharer.php?u=http://www.teddypintat.fr/greenCityzen/auth/album/greenpodid/<?php echo $this->greenId;?>&t=" rel="nofollow" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=500,width=700');return false;"><img src="<?php echo $this->baseUrl();?>/images/facebook_2.png" alt="bouton partage facebook" width="50" height="50"/></a>
        
        <a target="_blank" title="Google +" href="https://plus.google.com/share?url=http://www.teddypintat.fr/greenCityzen/auth/album/greenpodid/<?php echo $this->greenId;?>&hl=fr" rel="nofollow" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=450,width=650');return false;"><img src="<?php echo $this->baseUrl();?>/images/googleplus_2.png" alt="bouton partage Google+" width="50" height="50"/></a>

         <a target="_blank" title="Pinterest" href="http://pinterest.com/pin/create/button/?description=http://http://www.teddypintat.fr/greenCityzen/auth/album/greenpodid/<?php echo $this->greenId;?>&hl=fr" rel="nofollow" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=450,width=650');return false;"><img src="<?php echo $this->baseUrl();?>/images/pinterest_2.png" alt="bouton partage Pinterest" width="50" height="50"/></a>

            </div>
</div>
<script type="text/javascript">

	$('#interface').removeClass('interface');
	$('#interface').addClass('interface2');
	$('#imglogo').addClass('displayNone');
	$('.Vue').addClass('backgroundJaune');
	$('#textDescription').html('<h2>Crier j\'adore</h2>');
	$('#texteDescription').html("<h1>Mon jardin dans ma rue</h1");
</script>